########################################################################
#
#    Vision Network - Python source code - file generated by vision
#    Tuesday 17 April 2007 09:11:03 
#    
#       The Scripps Research Institute (TSRI)
#       Molecular Graphics Lab
#       La Jolla, CA 92037, USA
#
# Copyright: Daniel Stoffler, Michel Sanner and TSRI
#   
# revision: Guillaume Vareille
#  
#########################################################################
#
# $Header: /opt/cvs/python/packages/share1.5/Vision/doc/Examples/matplotlib/RandomNormDist_net.py,v 1.2 2007/08/29 20:37:16 vareille Exp $
#
# $Id: RandomNormDist_net.py,v 1.2 2007/08/29 20:37:16 vareille Exp $
#

from traceback import print_exc
## loading libraries ##
from Vision.matplotlibNodes import matplotliblib
masterNet.getEditor().addLibraryInstance(matplotliblib,"Vision.matplotlibNodes", "matplotliblib")

try:
    ## saving node RandNormDist ##
    from Vision.matplotlibNodes import RandNormDist
    RandNormDist_7 = RandNormDist(constrkw = {}, name='RandNormDist', library=matplotliblib)
    masterNet.addNode(RandNormDist_7,70,37)
    apply(RandNormDist_7.configure, (), {'expanded': True})
except:
    print "WARNING: failed to restore RandNormDist named RandNormDist in network masterNet"
    print_exc()
    RandNormDist_7=None

try:
    ## saving node Histogram ##
    from Vision.matplotlibNodes import HistogramNE
    Histogram_9 = HistogramNE(constrkw = {}, name='Histogram', library=matplotliblib)
    masterNet.addNode(Histogram_9,117,182)
    apply(Histogram_9.configure, (), {'expanded': True})
except:
    print "WARNING: failed to restore HistogramNE named Histogram in network masterNet"
    print_exc()
    Histogram_9=None

masterNet.freeze()

## saving connections for network new ##
if RandNormDist_7 is not None and Histogram_9 is not None:
    try:
        masterNet.connectNodes(
            RandNormDist_7, Histogram_9, "data", "values", blocking=True)
    except:
        print "WARNING: failed to restore connection between RandNormDist_7 and Histogram_9 in network masterNet"
masterNet.unfreeze()
#masterNet.run()

