# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _gle
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


TUBE_JN_RAW = _gle.TUBE_JN_RAW
TUBE_JN_ANGLE = _gle.TUBE_JN_ANGLE
TUBE_JN_CUT = _gle.TUBE_JN_CUT
TUBE_JN_ROUND = _gle.TUBE_JN_ROUND
TUBE_JN_MASK = _gle.TUBE_JN_MASK
TUBE_JN_CAP = _gle.TUBE_JN_CAP
TUBE_NORM_FACET = _gle.TUBE_NORM_FACET
TUBE_NORM_EDGE = _gle.TUBE_NORM_EDGE
TUBE_NORM_PATH_EDGE = _gle.TUBE_NORM_PATH_EDGE
TUBE_NORM_MASK = _gle.TUBE_NORM_MASK
TUBE_CONTOUR_CLOSED = _gle.TUBE_CONTOUR_CLOSED
GLE_TEXTURE_ENABLE = _gle.GLE_TEXTURE_ENABLE
GLE_TEXTURE_STYLE_MASK = _gle.GLE_TEXTURE_STYLE_MASK
GLE_TEXTURE_VERTEX_FLAT = _gle.GLE_TEXTURE_VERTEX_FLAT
GLE_TEXTURE_NORMAL_FLAT = _gle.GLE_TEXTURE_NORMAL_FLAT
GLE_TEXTURE_VERTEX_CYL = _gle.GLE_TEXTURE_VERTEX_CYL
GLE_TEXTURE_NORMAL_CYL = _gle.GLE_TEXTURE_NORMAL_CYL
GLE_TEXTURE_VERTEX_SPH = _gle.GLE_TEXTURE_VERTEX_SPH
GLE_TEXTURE_NORMAL_SPH = _gle.GLE_TEXTURE_NORMAL_SPH
GLE_TEXTURE_VERTEX_MODEL_FLAT = _gle.GLE_TEXTURE_VERTEX_MODEL_FLAT
GLE_TEXTURE_NORMAL_MODEL_FLAT = _gle.GLE_TEXTURE_NORMAL_MODEL_FLAT
GLE_TEXTURE_VERTEX_MODEL_CYL = _gle.GLE_TEXTURE_VERTEX_MODEL_CYL
GLE_TEXTURE_NORMAL_MODEL_CYL = _gle.GLE_TEXTURE_NORMAL_MODEL_CYL
GLE_TEXTURE_VERTEX_MODEL_SPH = _gle.GLE_TEXTURE_VERTEX_MODEL_SPH
GLE_TEXTURE_NORMAL_MODEL_SPH = _gle.GLE_TEXTURE_NORMAL_MODEL_SPH
gleDestroyGC = _gle.gleDestroyGC
gleGetJoinStyle = _gle.gleGetJoinStyle
gleSetJoinStyle = _gle.gleSetJoinStyle
gleGetNumSides = _gle.gleGetNumSides
gleSetNumSides = _gle.gleSetNumSides
glePolyCylinder = _gle.glePolyCylinder
glePolyCylinder_c4f = _gle.glePolyCylinder_c4f
glePolyCone = _gle.glePolyCone
glePolyCone_c4f = _gle.glePolyCone_c4f
gleExtrusion = _gle.gleExtrusion
gleExtrusion_c4f = _gle.gleExtrusion_c4f
gleTwistExtrusion = _gle.gleTwistExtrusion
gleTwistExtrusion_c4f = _gle.gleTwistExtrusion_c4f
gleSuperExtrusion = _gle.gleSuperExtrusion
gleSuperExtrusion_c4f = _gle.gleSuperExtrusion_c4f
gleSpiral = _gle.gleSpiral
gleLathe = _gle.gleLathe
gleHelicoid = _gle.gleHelicoid
gleToroid = _gle.gleToroid
gleScrew = _gle.gleScrew
gleTextureMode = _gle.gleTextureMode
rot_axis = _gle.rot_axis
rot_about_axis = _gle.rot_about_axis
rot_omega = _gle.rot_omega
rot_prince = _gle.rot_prince
urot_axis = _gle.urot_axis
urot_about_axis = _gle.urot_about_axis
urot_omega = _gle.urot_omega
urot_prince = _gle.urot_prince
uview_direction = _gle.uview_direction
uviewpoint = _gle.uviewpoint
gleFeedBack = _gle.gleFeedBack
gleFreeFeedbackBuffers = _gle.gleFreeFeedbackBuffers

gleGetTriangleMesh = _gle.gleGetTriangleMesh

