cmdlist = [
("ViewerFramework","customizationCommands","setUserPreference",""" Command providing a GUI to allow the user to set available\n    userPreference."""),
("ViewerFramework","customizationCommands","setOnAddObjectCommands","""Command to specify commands that have to be carried out when an object\n    is added to the application. Only the commands that have been loaded so\n    far in the application will appear in the GUI. Commands are applied in\n    the order they have been selected.\n    """),
("ViewerFramework","customizationCommands","saveSession","""Command to allow the user to save the session as it is in a file.\n    It copies the .pmvrc in that file and also log all the transformation."""),
("ViewerFramework","customizationCommands","source","""\n    Command to source a command file\n    """),
("ViewerFramework","customizeVFGUICommands","changeFont",""" Command to change font of the VFGUI"""),
("ViewerFramework","customizeVFGUICommands","showHideGUI",""" Command to change which parts of the VFGUI are visible"""),
("ViewerFramework","customizeVFGUICommands","bindAction",""""""),
("ViewerFramework","customizeVFGUICommands","hideGUI","""\n    Allow to Hide the  ViewerFrameworkGUI at any time """),
("ViewerFramework","customizeVFGUICommands","showGUI","""\n    Allow to show the ViewerFrameworkGUI at any time"""),
("ViewerFramework","dejaVuCommands","transformObject",""""""),
("ViewerFramework","dejaVuCommands","setObject",""""""),
("ViewerFramework","dejaVuCommands","setCamera",""""""),
("ViewerFramework","dejaVuCommands","setLight",""""""),
("ViewerFramework","dejaVuCommands","setClip",""""""),
("ViewerFramework","dejaVuCommands","addClipPlane",""""""),
("ViewerFramework","dejaVuCommands","centerGeom",""""""),
("ViewerFramework","dejaVuCommands","viewPoints","""None <- view(name, mode='save' or 'restore')\n    Command to save current transformation of root node\n    """),
("ViewerFramework","dejaVuCommands","centerScene","""None <- centerScene()\n    Command to scale and translate the scene to make it fit in the view frustum\n    """),
("ViewerFramework","dejaVuCommands","rotateScene","""None <- rotateScene(axis, stepSize, nbSteps)\n    Command to rotate the scene about an arbitrary axis nbSteps times\n    (default full turn) by stepSize degrees (default 5)\n    """),
("ViewerFramework","dejaVuCommands","printGeometryName",""""""),
("ViewerFramework","dejaVuCommands","startContinuousPicking","""Start the contiguous selection mode"""),
("ViewerFramework","dejaVuCommands","stopContinuousPicking",""""""),
("ViewerFramework","documentationCommands","helpCommand",""""""),
("ViewerFramework","serverCommands","startServer",""" This class implements methods to start a server"""),
("ViewerFramework","serverCommands","connectToServer",""" This class implements method to connect to a server."""),
]
