# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _glf
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


glfGet3DSolidStringTriangles = _glf.glfGet3DSolidStringTriangles
GLF_ERROR = _glf.GLF_ERROR
GLF_OK = _glf.GLF_OK
GLF_YES = _glf.GLF_YES
GLF_NO = _glf.GLF_NO
GLF_CONSOLE_MESSAGES = _glf.GLF_CONSOLE_MESSAGES
GLF_TEXTURING = _glf.GLF_TEXTURING
GLF_CONTOURING = _glf.GLF_CONTOURING
GLF_LEFT_UP = _glf.GLF_LEFT_UP
GLF_LEFT_CENTER = _glf.GLF_LEFT_CENTER
GLF_LEFT_DOWN = _glf.GLF_LEFT_DOWN
GLF_CENTER_UP = _glf.GLF_CENTER_UP
GLF_CENTER_CENTER = _glf.GLF_CENTER_CENTER
GLF_CENTER_DOWN = _glf.GLF_CENTER_DOWN
GLF_RIGHT_UP = _glf.GLF_RIGHT_UP
GLF_RIGHT_CENTER = _glf.GLF_RIGHT_CENTER
GLF_RIGHT_DOWN = _glf.GLF_RIGHT_DOWN
GLF_CENTER = _glf.GLF_CENTER
GLF_LEFT = _glf.GLF_LEFT
GLF_RIGHT = _glf.GLF_RIGHT
GLF_UP = _glf.GLF_UP
GLF_DOWN = _glf.GLF_DOWN
GLF_CONSOLE_CURSOR = _glf.GLF_CONSOLE_CURSOR
glfInit = _glf.glfInit
glfClose = _glf.glfClose
glfLoadFont = _glf.glfLoadFont
glfLoadBMFFont = _glf.glfLoadBMFFont
glfUnloadFont = _glf.glfUnloadFont
glfUnloadBMFFont = _glf.glfUnloadBMFFont
glfUnloadFontD = _glf.glfUnloadFontD
glfUnloadBMFFontD = _glf.glfUnloadBMFFontD
glfDrawWiredSymbol = _glf.glfDrawWiredSymbol
glfDrawWiredString = _glf.glfDrawWiredString
glfDrawSolidSymbol = _glf.glfDrawSolidSymbol
glfDrawSolidString = _glf.glfDrawSolidString
glfDraw3DWiredSymbol = _glf.glfDraw3DWiredSymbol
glfDraw3DWiredString = _glf.glfDraw3DWiredString
glfDraw3DSolidSymbol = _glf.glfDraw3DSolidSymbol
glfDraw3DSolidString = _glf.glfDraw3DSolidString
glfStartBitmapDrawing = _glf.glfStartBitmapDrawing
glfStopBitmapDrawing = _glf.glfStopBitmapDrawing
glfDrawBSymbol = _glf.glfDrawBSymbol
glfDrawBString = _glf.glfDrawBString
glfDrawBMaskSymbol = _glf.glfDrawBMaskSymbol
glfDrawBMaskString = _glf.glfDrawBMaskString
glfDrawWiredSymbolF = _glf.glfDrawWiredSymbolF
glfDrawWiredStringF = _glf.glfDrawWiredStringF
glfDrawSolidSymbolF = _glf.glfDrawSolidSymbolF
glfDrawSolidStringF = _glf.glfDrawSolidStringF
glfDraw3DWiredSymbolF = _glf.glfDraw3DWiredSymbolF
glfDraw3DWiredStringF = _glf.glfDraw3DWiredStringF
glfDraw3DSolidSymbolF = _glf.glfDraw3DSolidSymbolF
glfDraw3DSolidStringF = _glf.glfDraw3DSolidStringF
glfGetStringBoundsF = _glf.glfGetStringBoundsF
glfGetStringBounds = _glf.glfGetStringBounds
glfSetSymbolSpace = _glf.glfSetSymbolSpace
glfGetSymbolSpace = _glf.glfGetSymbolSpace
glfSetSpaceSize = _glf.glfSetSpaceSize
glfGetSpaceSize = _glf.glfGetSpaceSize
glfSetSymbolDepth = _glf.glfSetSymbolDepth
glfGetSymbolDepth = _glf.glfGetSymbolDepth
glfSetCurrentFont = _glf.glfSetCurrentFont
glfSetCurrentBMFFont = _glf.glfSetCurrentBMFFont
glfGetCurrentFont = _glf.glfGetCurrentFont
glfGetCurrentBMFFont = _glf.glfGetCurrentBMFFont
glfSetAnchorPoint = _glf.glfSetAnchorPoint
glfSetContourColor = _glf.glfSetContourColor
glfEnable = _glf.glfEnable
glfDisable = _glf.glfDisable
glfSetConsoleParam = _glf.glfSetConsoleParam
glfSetConsoleFont = _glf.glfSetConsoleFont
glfConsoleClear = _glf.glfConsoleClear
glfPrint = _glf.glfPrint
glfPrintString = _glf.glfPrintString
glfPrintChar = _glf.glfPrintChar
glfConsoleDraw = _glf.glfConsoleDraw
glfSetCursorBlinkRate = _glf.glfSetCursorBlinkRate
glfStringCentering = _glf.glfStringCentering
glfGetStringCentering = _glf.glfGetStringCentering
glfBitmapStringCentering = _glf.glfBitmapStringCentering
glfBitmapGetStringCentering = _glf.glfBitmapGetStringCentering
glfStringDirection = _glf.glfStringDirection
glfGetStringDirection = _glf.glfGetStringDirection
glfSetRotateAngle = _glf.glfSetRotateAngle
glfSetBRotateAngle = _glf.glfSetBRotateAngle

cvar = _glf.cvar

