; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9155A77B-6987-4D53-882C-36E14667DEC4}
AppName=Molecular Flipbook
AppVersion=0.1 Beta
AppPublisherURL=http://molecularflipbook.org
AppSupportURL=http://molecularflipbook.org
AppUpdatesURL=http://molecularflipbook.org
DefaultDirName={pf}\MolecularFlipbook
DefaultGroupName=Molecular Flipbook
DisableProgramGroupPage=yes
OutputBaseFilename=setup
SetupIconFile= asset\art\iconComposer.ico
Compression=lzma
SolidCompression=yes
ChangesAssociations=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "..\release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Molecular Flipbook"; Filename: "{app}\MolecularFlipbook.exe"
Name: "{group}\Molecular Flipbook (with console)"; Filename: "{app}\MolecularFlipbook.exe"; Parameters:"-c"
Name: "{group}\{cm:ProgramOnTheWeb,Molecular Flipbook}"; Filename: "http://molecularflipbook.org"

[Registry]
Root: HKCR; Subkey: ".flipbook"; ValueType: string; ValueName: ""; ValueData: "MolecularFlipbook"; Flags: uninsdeletevalue
Root: HKCR; Subkey: "MolecularFlipbook"; ValueType: string; ValueName: ""; ValueData: "Molecular Flipbook File"; Flags: uninsdeletekey
Root: HKCR; Subkey: "MolecularFlipbook\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\MolecularFlipbook.exe,0"
Root: HKCR; Subkey: "MolecularFlipbook\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\MolecularFlipbook.exe"" ""%1"""

[Run]
Filename: "{app}\MolecularFlipbook.exe"; Description: "{cm:LaunchProgram,Molecular Flipbook}"; Flags: nowait postinstall skipifsilent
